# To define global variables
variables:
  IMG: "MY_BUILT_IMG"
  PROD_LINUX_SERVER: "MY_PRODUCTION_LINUX_SERVER_URL"
  PROD_WINDOWS_SERVER: "MY_PRODUCTION_WINDOWS_SERVER_URL"

stages:
  - syntax
  - test
  - build
  - deploy

shell_syntax:
  tags:
    - Linux
  image: ${IMG}
  stage: syntax
  script:
    - apt install shellcheck -y
    # Shellcheck is an example to check SHELL scripts syntax
    - shellcheck *.sh scripts/*.sh

python_syntax:
  tags:
    - Linux
  image: ${IMG}
  stage: syntax
  script:
    - pip install pip setuptools wheel --upgrade
    - pip install -r requirements.txt --upgrade
    - pylint my_project

test:
  tags:
    - Linux
  image: ${IMG}
  stage: test
  variables:
    MY_SERVER_URL: "MY_URL"
  script:
    - pip install pip setuptools wheel --upgrade
    - pip install -r requirements.txt --upgrade
    - python3 setup.py develop
    - pytest -v --cov=my_project --ignore=tests/functional --cov-report term-missing

linux_build:
  tags:
    - Linux
  image: ${IMG}
  stage: build
  variables:
    MY_SERVER_URL: "MY_URL"
  script:
    - pip install pip setuptools wheel --upgrade
    - build_debian_image.sh
  artifacts:
    expire_in: 1 week
    paths:
      - ./debuild
    when: on_success
  only:
    - tags

windows_build:
  stage: build
  tags:
    - Windows
  variables:
    MY_SERVER_URL: "MY_URL"
  script:
    - python -m pip install pip wheel --upgrade
    - build_windows_image.bat
  artifacts:
    expire_in: 1 week
    paths:
      - build\exe.win32\my_project.msi
    when: on_success
  only:
    - tags

linux_deploy:
  tags:
    - Linux
  image: ${IMG}
  stage: deploy
  script:
    - cd debuild
    - dput ${PROD_LINUX_SERVER} my_project_VERSION_amd64.changes 
  only:
    - tags
  dependencies:
    - build_linux
  when: manual

windows_deploy:
  tags:
    - Linux
  image: ${IMG}
  stage: deploy
  script:
    - DEST_DIR=$(if [[ "${CI_COMMIT_TAG}" =~ "beta" ]]; then echo "testing"; else echo "stable"; fi)
    - echo "${PROD_WINDOWS_SERVER}" > /password-repo.key
    - echo "put build/exe.win32/*.msi /" | sshpass -f /password-repo.key sftp -oBatchMode=no -oStrictHostKeyChecking=no -b - USERNAME@${PROD_WINDOWS_SERVER}
  only:
    - tags
  dependencies:
    - build_windows
  when: manual